src/Entity/Project.php
<?php

namespace App\Entity;

use App\Repository\ProjectRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;

#[ORM\Entity(repositoryClass: ProjectRepository::class)]
class Project
{
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255, unique: true, nullable: true)]
    #[Gedmo\Slug(fields: ['name'], updatable: true, unique: true)]
    protected ?string $slug = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: "boolean", options: ['default' => 0])]
    private bool $active = false;

    #[ORM\ManyToOne(targetEntity: User::class, cascade: ['persist'])]
    #[ORM\JoinColumn(name: 'user_id', nullable: true, onDelete: 'SET NULL')]
    private ?User $createdBy = null;

    #[ORM\ManyToOne(targetEntity: OrganizationUnit::class, cascade: ['persist'])]
    #[ORM\JoinColumn(name: 'organization_unit_id', nullable: false)]
    private ?OrganizationUnit $organizationUnit = null;

    #[ORM\OneToMany(mappedBy: "project", targetEntity: ProjectUser::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    private iterable $users;

    #[ORM\OneToMany(mappedBy: "project", targetEntity: ProjectFile::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    private iterable $files;

    #[ORM\ManyToOne(targetEntity: ProjectCategoryReference::class, cascade: ['persist'])]
    #[ORM\JoinColumn(name: 'project_category_reference_id', nullable: true)]
    private ?ProjectCategoryReference $projectCategoryReference = null;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->files = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;
        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function isActive(): bool
    {
        return $this->active;
    }

    public function setActive(bool $active): Project
    {
        $this->active = $active;
        return $this;
    }


    public function getCreatedBy(): ?User
    {
        return $this->createdBy;
    }

    public function setCreatedBy(?User $createdBy): self
    {
        $this->createdBy = $createdBy;
        if ($createdBy instanceof User) {
            $this->addUser($createdBy, [ProjectUser::FULL_PRIVILEGE]);
        }
        return $this;
    }

    public function getOrganizationUnit(): ?OrganizationUnit
    {
        return $this->organizationUnit;
    }

    public function setOrganizationUnit(?OrganizationUnit $organizationUnit): self
    {
        $this->organizationUnit = $organizationUnit;
        return $this;
    }

    /**
     * @return Collection<ProjectUser>
     */
    public function getProjectUsers(): Collection
    {
        return $this->users;
    }

    /**
     * @return Collection<ProjectUser>
     */
    public function getProjectUsersWithoutOwner(): Collection
    {
        return $this->users->filter(function (ProjectUser $projectUser) {
            return $projectUser->getUser() !== $this->getCreatedBy();
        });
    }

    public function addProjectUsersWithoutOwner(ProjectUser $projectUser): self
    {
        return $this->addProjectUser($projectUser);
    }

    public function removeProjectUsersWithoutOwner(ProjectUser $projectUser): self
    {
        return $this->removeProjectUser($projectUser);
    }

    public function addProjectUser(ProjectUser $projectUser): self
    {
        $projectUser->setProject($this);
        $users = $this->getUsers()->filter(function (User $forUser) use ($projectUser) {
            return $forUser === $projectUser->getUser();
        });
        if ($users->isEmpty()) {
            $this->users->add($projectUser);
        }
        return $this;
    }

    public function removeProjectUser(ProjectUser $projectUser): self
    {
        return $this->removeUser($projectUser->getUser());
    }

    public function getUsers(): Collection
    {
        return $this->users->map(function (ProjectUser $projectUser) {
            return $projectUser->getUser();
        });
    }

    public function addUser(User $user, array $permissions = [ProjectUser::CAN_CREATE_TASK]): self
    {
        $projectUser = (new ProjectUser())
            ->setPermissions($permissions)
            ->setUser($user);

        return $this->addProjectUser($projectUser);
    }

    public function removeUser(User $user): self
    {
        foreach ($this->getProjectUsers() as $projectUser) {
            if ($projectUser->getUser() === $user) {
                $this->getProjectUsers()->removeElement($projectUser);
            }
        }
        return $this;
    }

    public function getFiles(): iterable
    {
        return $this->files;
    }

    public function addFile(ProjectFile $file): self
    {
        $file->setProject($this);
        if (!$this->files->contains($file)) {
            $this->files->add($file);
        }
        return $this;
    }

    public function getProjectCategoryReference(): ?ProjectCategoryReference
    {
        return $this->projectCategoryReference;
    }

    public function setProjectCategoryReference(?ProjectCategoryReference $projectCategoryReference): self
    {
        $this->projectCategoryReference = $projectCategoryReference;
        return $this;
    }

    public function canAccess(User $user): bool
    {
        if ($user->isSuperAdmin()) {
            return true;
        }

        if ($user->isAdmin() && $user->getOrganizationUnit() === $this->getOrganizationUnit()) {
            return true;
        }
        if ($this->getUsers()->contains($user)) {
            return true;
        }

        return false;
    }

    public function canEditProject(User $user): bool
    {
        if ($user->isSuperAdmin()) {
            return true;
        }

        if ($user->isAdmin() && $user->getOrganizationUnit() === $this->getOrganizationUnit()) {
            return true;
        }

        foreach ($this->getProjectUsers() as $projectUser) {
            if ($projectUser->getUser() === $user && $projectUser->canEditProject()) {
                return true;
            }
        }
        return false;
    }

    public function canCloseProject(User $user): bool
    {
        if ($user->isSuperAdmin()) {
            return true;
        }

        if ($user->isAdmin() && $user->getOrganizationUnit() === $this->getOrganizationUnit()) {
            return true;
        }

        foreach ($this->getProjectUsers() as $projectUser) {
            if ($projectUser->getUser() === $user && $projectUser->canCloseProject()) {
                return true;
            }
        }
        return false;
    }

    public function canCreateTask(User $user): bool
    {
        if ($user->isSuperAdmin()) {
            return true;
        }

        if ($user->isAdmin() && $user->getOrganizationUnit() === $this->getOrganizationUnit()) {
            return true;
        }

        foreach ($this->getProjectUsers() as $projectUser) {
            if ($projectUser->getUser() === $user && $projectUser->canCreateTask()) {
                return true;
            }
        }
        return false;
    }
}

src/Controller/ProjectController.php
<?php

namespace App\Controller;

use App\Entity\File;
use App\Entity\OrganizationUnit;
use App\Entity\Project;
use App\Entity\ProjectCategoryReference;
use App\Entity\ProjectCategoryReferenceStatus;
use App\Entity\ProjectFile;
use App\Entity\TaskStatusReference;
use App\Entity\User;
use App\Form\ProjectType;
use App\Repository\ProjectCategoryReferenceRepository;
use App\Repository\ProjectRepository;
use App\Repository\ProjectUserRepository;
use App\Repository\TaskRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\HeaderUtils;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

#[Route('/projects')]
class ProjectController extends AbstractController
{

    public function __construct(private readonly EntityManagerInterface $em, private readonly TranslatorInterface $translator)
    {
    }

    #[Route('', name: 'projects_index')]
    public function index(ProjectRepository $projectRepository, ProjectUserRepository $projectUserRepository): Response
    {
        /**
         * @var User $user
         */
        $user = $this->getUser();

        if ($this->isGranted('ROLE_SUPER_ADMIN')) {
            $projects = $projectRepository->findBy([], ['id' => 'DESC']);
        }
        elseif ($this->isGranted('ROLE_ADMIN')) {
            $projects = $projectRepository->findByOrganizationUnit($user->getOrganizationUnit());
        }
        else {
            $projects = [];
            foreach ($projectUserRepository->findAllByUser($user) as $projectUser) {
                $projects[] = $projectUser->getProject();
            }
        }

        return $this->render('project/index.html.twig', [
            'projects' => $projects
        ]);
    }

    #[Route('/orgUnit/{organizationUnit}/create', name: 'projects_add')]
    public function add(Request $request, OrganizationUnit $organizationUnit, ProjectCategoryReferenceRepository $projectCategoryReferenceRepository): Response
    {
        /**
         * @var User $user
         */
        $user = $this->getUser();

        if ($user->getOrganizationUnit() !== $organizationUnit) {
            throw new AccessDeniedHttpException();
        }

        if ($projectCategoryReferenceRepository->count(['organizationUnit' => $organizationUnit]) === 0) {
            $this->addFlash('error', $this->translator->trans('not_exist_project_category_reference'));
            return $this->redirectToRoute('projects_index');
        }

        return $this->form(
            $request,
            (new Project())
                ->setOrganizationUnit($organizationUnit)
                ->setActive(true)
                ->setCreatedBy($user)
        );
    }

    #[Route('/edit/{project}', name: 'projects_edit')]
    public function edit(Request $request, Project $project): Response
    {
        /**
         * @var User $user
         */
        $user = $this->getUser();
        if (!$project->canEditProject($user)) {
            throw new AccessDeniedHttpException();
        }

        return $this->form($request, $project);
    }

    private function form(Request $request, Project $project): Response
    {
        $form = $this->createForm(ProjectType::class, $project, [
            'organization_unit' => $project->getOrganizationUnit()
        ]);
        if ($form->handleRequest($request)->isSubmitted() && $form->isValid()) {

            /**
             * @var UploadedFile $uploadedFile
             */
            foreach ($form->get('files')->getData() as $uploadedFile) {
                $projectFile = (new ProjectFile())
                    ->setFile(
                        (new File())
                            ->setName($uploadedFile->getClientOriginalName())
                            ->setSize($uploadedFile->getSize())
                            ->setMimeType($uploadedFile->getMimeType())
                            ->setContent($uploadedFile->getContent())
                    );
                $project->addFile($projectFile);
            }

            $this->em->persist($project);
            $this->em->flush();
            $this->addFlash('success', $this->translator->trans('project_saved_successfully'));
            return $this->redirectToRoute('projects_get', ['slug' => $project->getSlug()]);
        }

        return $this->render('project/form.html.twig', [
            'form' => $form->createView(),
            'project' => $project
        ]);
    }

    #[Route('/{slug}', name: 'projects_get')]
    public function project(Project $project, TaskRepository $taskRepository): Response
    {

        /**
         * @var User $user
         */
        $user = $this->getUser();
        if (!$project->canAccess($user)) {
            throw new AccessDeniedHttpException();
        }

        /**
         * @var array<ProjectCategoryReferenceStatus> $statuses
         */
        $statuses = $project->getProjectCategoryReference()?->getProjectCategoryReferenceStatuses() ?: [];

        return $this->render('project/project.html.twig', [
            'project' => $project,
            'tasks' => $taskRepository->findByProject($project),
            'statuses' => $statuses
        ]);
    }

    #[Route('/close/{project}', name: 'projects_close')]
    public function close(Request $request, Project $project): Response
    {
        /**
         * @var User $user
         */
        $user = $this->getUser();
        if (!$project->canCloseProject($user)) {
            throw new AccessDeniedHttpException();
        }

        $project->setActive(false);
        $this->em->flush();
        $this->addFlash('success', $this->translator->trans('project_closed_successfully', ['%project_id%' => $project->getId()]));

        return $this->redirectReferer($request);
    }

    #[Route('/open/{project}', name: 'projects_open')]
    public function open(Request $request, Project $project): Response
    {
        /**
         * @var User $user
         */
        $user = $this->getUser();
        if (!$project->canCloseProject($user)) {
            throw new AccessDeniedHttpException();
        }

        $project->setActive(true);
        $this->em->flush();
        $this->addFlash('success', $this->translator->trans('project_reopened_successfully', ['%project_id%' => $project->getId()]));

        return $this->redirectReferer($request);
    }

    #[Route('/file/{uid}', name: 'projects_file', methods: ['GET'])]
    public function projectFile(Request $request, projectFile $projectFile): Response
    {
        /**
         * @var User $user
         */
        $user = $this->getUser();
        $project = $projectFile->getProject();
        if (!$project->canAccess($user)) {
            throw new AccessDeniedHttpException();
        }

        $file = $projectFile->getFile();
        if (!$file instanceof File) {
            throw new NotFoundHttpException();
        }
        $response = new Response(stream_get_contents($file->getContent()));

        if ($file->getMimeType() == 'application/pdf') {
            $response->headers->set('Content-Type', 'application/pdf');
            $disposition = HeaderUtils::makeDisposition(
                HeaderUtils::DISPOSITION_INLINE,
                $file->getName()
            );
        } else {
            $disposition = HeaderUtils::makeDisposition(
                HeaderUtils::DISPOSITION_ATTACHMENT,
                $file->getName()
            );
        }

        $response->headers->set('Content-Disposition', $disposition);
        return $response;
    }

    private function redirectReferer(Request $request): Response
    {
        $referer = $request->headers->get('referer');
        if ($referer) {
            return $this->redirect($referer);
        }

        return $this->redirectToRoute('projects_index');
    }
}

templates/project/form.html.twig
{% extends 'base.html.twig' %}
{% block content %}
    <div class="mt-2">
        <div class="card mt-2">
            <div class="card-header">
                <h5>📝 {{ project.name|default('New Project')|trans }}</h5>
            </div>
            <div class="card-body container">
                {{ form_start(form) }}
                {{ form_row(form.projectCategoryReference) }}
                {{ form_row(form.name) }}
                {{ form_row(form.description) }}
                {{ form_row(form.files) }}
                <div class="small">
                    <h5>{{ 'Members' | trans }}</h5>
                    <ul id="project_users" class="members list-group"
                        data-index="{{ form.projectUsersWithoutOwner|length > 0 ? form.projectUsersWithoutOwner|last.vars.name + 1 : 0 }}"
                        data-prototype="{{ form_widget(form.projectUsersWithoutOwner.vars.prototype)|e('html_attr') }}"
                    >
                        {% for projectUser in form.projectUsersWithoutOwner %}
                            <li class="list-group-item item-from-collection">
                                {{ form_row(projectUser.user) }}
                                {{ form_row(projectUser.permissions) }}
                            </li>
                        {% endfor %}
                    </ul>
                    <button type="button" class="add_item_link btn btn-outline-success btn-sm mt-1" data-collection-holder-class="members">{{ 'Add a member' | trans }}</button>
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script>

        function initSelect(item) {
            item.querySelectorAll('.form-select').forEach((select) => {
                new TomSelect(select, {plugins: ['remove_button'],});
            })
        }

        const addFormToCollection = (e) => {
            const collectionHolder = document.querySelector('.' + e.currentTarget.dataset.collectionHolderClass);

            const item = document.createElement('li');
            item.classList.add('list-group-item', 'item-from-collection')

            item.innerHTML = collectionHolder
                .dataset
                .prototype
                .replace(
                    /__name__/g,
                    collectionHolder.dataset.index
                );

            collectionHolder.appendChild(item);

            collectionHolder.dataset.index++;
            addTagFormDeleteLink(item);
            initSelect(item);
        };

        const addTagFormDeleteLink = (item) => {
            const removeFormButton = document.createElement('button');
            removeFormButton.innerText = '🗑️';
            removeFormButton.classList.add('btn', 'btn-danger', 'btn-sm', 'item-delete-btn')

            item.append(removeFormButton);

            removeFormButton.addEventListener('click', (e) => {
                e.preventDefault();
                // remove the li for the tag form
                item.remove();
            });
        }

        document.addEventListener('DOMContentLoaded', function () {

            var easyMDE  = new EasyMDE({
                element: document.getElementById("project_description"),
                minHeight: "200px",
                status: false,
                toolbar: ["undo", "bold", "italic", "heading", "unordered-list", "ordered-list", "|","code", "|", "preview"],
                timeFormat: {
                    format: {
                        year: 'numeric',
                        month: 'long',
                        day: '2-digit',
                        hour: '2-digit',
                        minute: '2-digit',
                    },
                },
            });

            document
                .querySelectorAll('.add_item_link')
                .forEach(btn => {
                    btn.addEventListener("click", addFormToCollection)
                });

            if (document.querySelector('#project_projectCategoryReference')) {
                const select = new TomSelect('#project_projectCategoryReference', {plugins: ['remove_button'],});
            }
            document.querySelectorAll('#project_users li').forEach((item) => {
                addTagFormDeleteLink(item)
                initSelect(item);
            })
        });
    </script>
{% endblock %}

templates/project/index.html.twig
{% extends 'base.html.twig' %}
{% block content %}
    <div class="mt-2">
        <div class="d-flex justify-content-between">
            <h1>{{ "Projects"|trans }}</h1>
            <div class="btn-group" role="group">
                <a href="{{ url('projects_add', {organizationUnit : app.user.organizationUnit.id}) }}" class="btn btn-outline-primary btn-sm">📝
                    {{ "New Project"|trans }}</a>
            </div>
        </div>
        <hr>
        <div class="table-responsive">
            <table class="table table-striped table-hover" id="projects">
                <thead>
                <tr>
                    <th scope="col">{{ 'ID'|trans }}</th>
                    <th scope="col">{{ 'Organization'|trans }}</th>
                    <th scope="col">{{ 'Category'|trans }}</th>
                    <th scope="col">{{ 'Project Name'|trans }}</th>
                    <th scope="col">{{ 'Description'|trans }}</th>
                    <th scope="col">{{ 'Status'|trans }}</th>
                    <th scope="col" data-sortable="false"></th>
                </tr>
                </thead>
                <tbody>
                {% for project in projects %}
                    <tr>
                        <th scope="row">{{ project.id }}</th>
                        <th scope="row">{{ project.organizationUnit.name }}</th>
                        <th scope="row">{{ project.projectCategoryReference.label|default('') }}</th>
                        <td><a href="{{ url('projects_get', {slug : project.slug}) }}">{{ project.name }}</a></td>
                        <td>{{ project.description|md2html|striptags|slice(0, 50) }}...</td>
                        <td>
                            {% if project.active is same as(true) %}
                                <span class="badge bg-success">{{ 'Active'|trans }}</span>
                            {% else %}
                                <span class="badge bg-danger">{{ 'Inactive'|trans }}</span>
                            {% endif %}
                        </td>
                        <td>
                            <div class="dropdown">
                                <button class="btn btn-light btn-sm dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false">
                                    ☰
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                    {% if project.active is same as(true) %}
                                        <li><a class="dropdown-item" href="{{ url('projects_close', {project: project.id}) }}">🔒 {{ 'Close'|trans }}</a></li>
                                    {% else %}
                                        <li><a class="dropdown-item" href="{{ url('projects_open', {project: project.id}) }}">🔓 {{ 'Open'|trans }}</a></li>
                                    {% endif %}
                                </ul>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script>
        window.addEventListener("DOMContentLoaded", (event) => {
            const dataTable = new DataTable("#projects", {
                searchable: true,
                perPage: 15,
                columns: [
                    {
                        select: 0,
                        sort: 'desc'
                    }
                ],
                labels: {
                    placeholder: "{{ 'Search...' | trans }}",
                    perPage: "{{ 'items per page' | trans }}",
                    noRows: "{{ 'No data' | trans }}",
                    info: "{{ 'Displaying {start} to {end} of {rows} items' | trans }}"
                }
            })
        });
    </script>
{% endblock %}